name: Python Package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.10", "3.11" , "3.12"]

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install ruff pytest uv numpy

    - name: Set up virtual environment
      run: |
        uv venv 
        source .venv/bin/activate
        # uv pip install .
        pip install -r ./requirements.txt

    # - name: Run static code analysis with Ruff
    #   run: |
    #     ruff check . --ignore F841

    - name: Run tests with pytest
      run: |
        pytest -x
